package Interface.Tela;

import Interface.Utilidade.RoundInput;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.*;

/**
 *
 * @author Sayu
 */
public class TelaRegistrarEvento extends JFrame {
    int xMouse;
    int yMouse;

    /**
     * Creates new form TelaRegistrarEvento
     */
    public TelaRegistrarEvento() {
        setUndecorated(true);
        
        initComponents();
        
        setSize(300, 425);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miniBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        EventLabel1 = new javax.swing.JLabel();
        EventField1 = new RoundInput();
        EventLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        EventLabel3 = new javax.swing.JLabel();
        EventField2 = new RoundInput();
        EventLabel4 = new javax.swing.JLabel();
        EventField3 = new RoundInput();
        EventLabel5 = new javax.swing.JLabel();
        EventField4 = new RoundInput();
        EventField5 = new RoundInput();
        EventLabel6 = new javax.swing.JLabel();
        EventLabel7 = new javax.swing.JLabel();
        EventField6 = new RoundInput();
        EventField7 = new RoundInput();
        EventLabel8 = new javax.swing.JLabel();
        EventLabel9 = new javax.swing.JLabel();
        EventField8 = new RoundInput();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        miniBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        miniBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miniBtn.setForeground(java.awt.Color.darkGray);
        miniBtn.setText("_");
        miniBtn.setBorder(null);
        miniBtn.setContentAreaFilled(false);
        miniBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniBtn.setFocusPainted(false);
        miniBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        miniBtn.setMaximumSize(new java.awt.Dimension(40, 30));
        miniBtn.setMinimumSize(new java.awt.Dimension(40, 30));
        miniBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        miniBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniBtnMouseExited(evt);
            }
        });
        miniBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitBtn.setForeground(java.awt.Color.darkGray);
        exitBtn.setText("x");
        exitBtn.setBorder(null);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setFocusPainted(false);
        exitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn.setMaximumSize(new java.awt.Dimension(40, 30));
        exitBtn.setMinimumSize(new java.awt.Dimension(40, 30));
        exitBtn.setPreferredSize(new java.awt.Dimension(40, 30));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        EventLabel1.setText("Nome do Evento:");

        EventField1.setText("Evento XYZ");
        EventField1.setMaximumSize(new java.awt.Dimension(250, 25));
        EventField1.setMinimumSize(new java.awt.Dimension(250, 25));
        EventField1.setPreferredSize(new java.awt.Dimension(250, 25));

        EventLabel2.setText("Descrição:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Descrição do Evento, e etc...");
        jTextArea1.setMaximumSize(new java.awt.Dimension(250, 50));
        jTextArea1.setMinimumSize(new java.awt.Dimension(250, 50));
        jTextArea1.setPreferredSize(new java.awt.Dimension(250, 50));
        jScrollPane1.setViewportView(jTextArea1);

        EventLabel3.setText("Data Início:");

        EventField2.setText("04/12/2025 14:00");
        EventField2.setMaximumSize(new java.awt.Dimension(171, 25));
        EventField2.setMinimumSize(new java.awt.Dimension(171, 25));
        EventField2.setPreferredSize(new java.awt.Dimension(171, 25));

        EventLabel4.setText("Data Final:");

        EventField3.setText("04/12/2025 14:00");
        EventField3.setMaximumSize(new java.awt.Dimension(171, 25));
        EventField3.setMinimumSize(new java.awt.Dimension(171, 25));
        EventField3.setPreferredSize(new java.awt.Dimension(171, 25));

        EventLabel5.setText("Loca do Evento:");

        EventField4.setText("Local");
        EventField4.setMaximumSize(new java.awt.Dimension(250, 25));
        EventField4.setMinimumSize(new java.awt.Dimension(250, 25));
        EventField4.setPreferredSize(new java.awt.Dimension(250, 25));

        EventField5.setText("30");
        EventField5.setMaximumSize(new java.awt.Dimension(75, 25));
        EventField5.setMinimumSize(new java.awt.Dimension(75, 25));
        EventField5.setPreferredSize(new java.awt.Dimension(75, 25));

        EventLabel6.setText("Convidados:");

        EventLabel7.setText("Diária(R$):");

        EventField6.setText("0.0");
        EventField6.setMaximumSize(new java.awt.Dimension(75, 25));
        EventField6.setMinimumSize(new java.awt.Dimension(75, 25));
        EventField6.setPreferredSize(new java.awt.Dimension(75, 25));

        EventField7.setText("0.0");
        EventField7.setMaximumSize(new java.awt.Dimension(171, 25));
        EventField7.setMinimumSize(new java.awt.Dimension(171, 25));
        EventField7.setPreferredSize(new java.awt.Dimension(171, 25));

        EventLabel8.setText("Longitude:");

        EventLabel9.setText("Latitude:");

        EventField8.setText("0.0");
        EventField8.setMaximumSize(new java.awt.Dimension(75, 25));
        EventField8.setMinimumSize(new java.awt.Dimension(75, 25));
        EventField8.setPreferredSize(new java.awt.Dimension(75, 25));

        jButton1.setBackground(new java.awt.Color(96, 63, 96));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Registrar");

        jButton2.setBackground(new java.awt.Color(189, 156, 189));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EventLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(miniBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(EventField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EventField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EventLabel3))
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EventLabel6)
                                        .addComponent(EventField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(EventLabel4)
                                        .addGap(116, 116, 116))
                                    .addComponent(EventField3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EventLabel7)
                                    .addComponent(EventField6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EventLabel8)
                                    .addComponent(EventField7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EventField8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EventLabel9)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EventLabel5)
                                .addComponent(EventField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EventLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EventField2, EventField3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(miniBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(EventLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(EventField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(EventLabel2)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventLabel3)
                    .addComponent(EventLabel6))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EventLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(EventField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EventLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(EventField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(EventLabel5)
                .addGap(2, 2, 2)
                .addComponent(EventField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventLabel8)
                    .addComponent(EventLabel9))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miniBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniBtnMouseEntered
        miniBtn.setBackground(Color.LIGHT_GRAY);
        miniBtn.setContentAreaFilled(true);
    }//GEN-LAST:event_miniBtnMouseEntered

    private void miniBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniBtnMouseExited
        miniBtn.setContentAreaFilled(false);
    }//GEN-LAST:event_miniBtnMouseExited

    private void miniBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniBtnActionPerformed
        new Thread(() -> {
            try {
                for (float i = 1.0f; i >= 0.0f; i -= 0.1f) {
                    setOpacity(i);
                    Thread.sleep(10);
                }
                setState(java.awt.Frame.ICONIFIED);
                setOpacity(1.0f);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }).start();
    }//GEN-LAST:event_miniBtnActionPerformed

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitBtn.setBackground(Color.red);
        exitBtn.setForeground(Color.white);
        exitBtn.setContentAreaFilled(true);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setBackground(Color.white);
        exitBtn.setForeground(Color.darkGray);
        exitBtn.setContentAreaFilled(false);
    }//GEN-LAST:event_exitBtnMouseExited

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EventField1;
    private javax.swing.JTextField EventField2;
    private javax.swing.JTextField EventField3;
    private javax.swing.JTextField EventField4;
    private javax.swing.JTextField EventField5;
    private javax.swing.JTextField EventField6;
    private javax.swing.JTextField EventField7;
    private javax.swing.JTextField EventField8;
    private javax.swing.JLabel EventLabel1;
    private javax.swing.JLabel EventLabel2;
    private javax.swing.JLabel EventLabel3;
    private javax.swing.JLabel EventLabel4;
    private javax.swing.JLabel EventLabel5;
    private javax.swing.JLabel EventLabel6;
    private javax.swing.JLabel EventLabel7;
    private javax.swing.JLabel EventLabel8;
    private javax.swing.JLabel EventLabel9;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton miniBtn;
    // End of variables declaration//GEN-END:variables
}
