package Interface;

import Controle.Controlador;
import Modelo.Categoria;
import Modelo.Localizacao;
import Modelo.Status;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Sayu
 */
public class MenuInicial extends javax.swing.JFrame {

    private Controlador controlador;

    public MenuInicial() {
        controlador = new Controlador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        criarOrganizador = new javax.swing.JButton();
        adicionarEvento = new javax.swing.JButton();
        cancelarEvento = new javax.swing.JButton();
        alterarDadosEvento = new javax.swing.JButton();
        exibirEvento = new javax.swing.JButton();
        exibirRelatorioEventos = new javax.swing.JButton();
        buscarEvento = new javax.swing.JButton();
        exibirNotificacoes = new javax.swing.JButton();
        adiconarComodidade = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));

        criarOrganizador.setBackground(new java.awt.Color(255, 204, 204));
        criarOrganizador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        criarOrganizador.setForeground(new java.awt.Color(204, 0, 51));
        criarOrganizador.setText("X Criar Organizador");
        criarOrganizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarOrganizadorActionPerformed(evt);
            }
        });

        adicionarEvento.setBackground(new java.awt.Color(255, 204, 204));
        adicionarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        adicionarEvento.setForeground(new java.awt.Color(204, 0, 51));
        adicionarEvento.setText("Adicionar Evento");
        adicionarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEventoActionPerformed(evt);
            }
        });

        cancelarEvento.setBackground(new java.awt.Color(255, 204, 204));
        cancelarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cancelarEvento.setForeground(new java.awt.Color(204, 0, 51));
        cancelarEvento.setText("Cancelar Evento");
        cancelarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEventoActionPerformed(evt);
            }
        });

        alterarDadosEvento.setBackground(new java.awt.Color(255, 204, 204));
        alterarDadosEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        alterarDadosEvento.setForeground(new java.awt.Color(204, 0, 51));
        alterarDadosEvento.setText("Alterar Dados do Evento");
        alterarDadosEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosEventoActionPerformed(evt);
            }
        });

        exibirEvento.setBackground(new java.awt.Color(255, 204, 204));
        exibirEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exibirEvento.setForeground(new java.awt.Color(204, 0, 51));
        exibirEvento.setText("X Exibir Evento");
        exibirEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirEventoActionPerformed(evt);
            }
        });

        exibirRelatorioEventos.setBackground(new java.awt.Color(255, 204, 204));
        exibirRelatorioEventos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exibirRelatorioEventos.setForeground(new java.awt.Color(204, 0, 51));
        exibirRelatorioEventos.setText("Exibir Relatório dos Eventos");
        exibirRelatorioEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirRelatorioEventosActionPerformed(evt);
            }
        });

        buscarEvento.setBackground(new java.awt.Color(255, 204, 204));
        buscarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buscarEvento.setForeground(new java.awt.Color(204, 0, 51));
        buscarEvento.setText("X Buscar Evento");

        exibirNotificacoes.setBackground(new java.awt.Color(255, 204, 204));
        exibirNotificacoes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exibirNotificacoes.setForeground(new java.awt.Color(204, 0, 51));
        exibirNotificacoes.setText("X Exibir Notificações");
        exibirNotificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirNotificacoesActionPerformed(evt);
            }
        });

        adiconarComodidade.setBackground(new java.awt.Color(255, 204, 204));
        adiconarComodidade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        adiconarComodidade.setForeground(new java.awt.Color(204, 0, 51));
        adiconarComodidade.setText("Adicionar Comodidade");
        adiconarComodidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiconarComodidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exibirRelatorioEventos)
                            .addComponent(criarOrganizador)
                            .addComponent(exibirNotificacoes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adicionarEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adiconarComodidade, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alterarDadosEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exibirEvento, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criarOrganizador)
                        .addGap(25, 25, 25)
                        .addComponent(exibirRelatorioEventos)
                        .addGap(25, 25, 25)
                        .addComponent(exibirNotificacoes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarEvento)
                        .addGap(25, 25, 25)
                        .addComponent(adicionarEvento)
                        .addGap(25, 25, 25)
                        .addComponent(adiconarComodidade)))
                .addGap(25, 25, 25)
                .addComponent(alterarDadosEvento)
                .addGap(25, 25, 25)
                .addComponent(exibirEvento)
                .addGap(29, 29, 29)
                .addComponent(cancelarEvento)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarOrganizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarOrganizadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_criarOrganizadorActionPerformed

    private void adicionarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEventoActionPerformed
        // TODO add your handling code here:
        // Criando os campos
        JTextField nomeField = new JTextField(15);
        JTextField descricaoField = new JTextField(15);
        JTextField quantidadeField = new JTextField(5);
        JTextField longitudeField = new JTextField(10);
        JTextField latitudeField = new JTextField(10);
        JTextField precoAcomodacao = new JTextField(10);
        JTextField nomeOrganizador = new JTextField(15);

        // Criando painel para organizar os inputs
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Descrição:"));
        panel.add(descricaoField);
        panel.add(new JLabel("Quantidade:"));
        panel.add(quantidadeField);
        panel.add(new JLabel("Longitude:"));
        panel.add(longitudeField);
        panel.add(new JLabel("Latitude:"));
        panel.add(latitudeField);
        panel.add(new JLabel("Preço Acomodação:"));
        panel.add(precoAcomodacao);
        panel.add(new JLabel("Nome Organizador:"));
        panel.add(nomeOrganizador);
        Component frame = null;

        // Exibindo o JOptionPane
        int result = JOptionPane.showConfirmDialog(
                frame, panel,
                "Preencha as informações",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        // Pegando os valores se o usuário clicar em OK
        if (result == JOptionPane.OK_OPTION) {
            Localizacao localizacao;
            localizacao = new Localizacao(Double.parseDouble(latitudeField.getText()), Double.parseDouble(longitudeField.getText()));
            controlador.adicionarEvento(nomeField.getText(), descricaoField.getText(), Integer.parseInt(quantidadeField.getText()), localizacao, Integer.parseInt(precoAcomodacao.getText()), nomeOrganizador.getText());
        }
    }//GEN-LAST:event_adicionarEventoActionPerformed

    private void exibirRelatorioEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirRelatorioEventosActionPerformed
        // TODO add your handling code here:
        String texto = controlador.exibirRelatorioEventos();
        JTextArea evento = new JTextArea(texto, 20, 50);
        evento.setLineWrap(true);
        evento.setWrapStyleWord(true);
        evento.setEditable(false);

        JScrollPane scroll = new JScrollPane(evento);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        JFrame frame = new JFrame("Exibição de Texto Grande");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(scroll);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_exibirRelatorioEventosActionPerformed

    private void cancelarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEventoActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(nomeField);
        Component frame = null;

        int result = JOptionPane.showConfirmDialog(
                frame, panel,
                "Evento a ser Cancelado",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = nomeField.getText();
            controlador.cancelarEvento(nomeEvento);
        }
    }//GEN-LAST:event_cancelarEventoActionPerformed

    private void alterarDadosEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosEventoActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JRadioButton agendado = new JRadioButton("Agendado", false);
        JRadioButton andamento = new JRadioButton("Em Andamento", false);
        JRadioButton finalizado = new JRadioButton("Finalizado", false);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(nomeField);
        panel.add(new JLabel("Status do Evento:"));
        panel.add(agendado);
        panel.add(andamento);
        panel.add(finalizado);
        Component frame = null;

        int result = JOptionPane.showConfirmDialog(
                frame, panel,
                "Evento a ser Alterado",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = nomeField.getText();
            if (agendado.isSelected()) {
                controlador.alterarStatusEvento(nomeEvento, Status.AGENDADO);
            }
            else if (andamento.isSelected()) {
                controlador.alterarStatusEvento(nomeEvento, Status.EM_ANDAMENTO);
            }
            else if (finalizado.isSelected()) {
                controlador.alterarStatusEvento(nomeEvento, Status.FINALIZADO);
            }
        }
    }//GEN-LAST:event_alterarDadosEventoActionPerformed

    private void exibirEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exibirEventoActionPerformed

    private void adiconarComodidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiconarComodidadeActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField comodidadeField = new JTextField(15);
        JTextField precoField = new JTextField(5);
        JRadioButton fixo = new JRadioButton("Custo Fixo", false);
        JRadioButton variavel = new JRadioButton("Custo Variavel", false);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(nomeField);
        panel.add(new JLabel("Nome da Comodidade:"));
        panel.add(comodidadeField);
        panel.add(new JLabel("Preço da Comodidade:"));
        panel.add(precoField);
        panel.add(new JLabel("Custo da Comodidade:"));
        panel.add(fixo);
        panel.add(variavel);
        
        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
                frame, panel,
                "Inserir Comodidade",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = nomeField.getText();
            String nomeComodidade = comodidadeField.getText();
            double preco = Double.parseDouble(precoField.getText());
            if (fixo.isSelected()) {
                controlador.adicionarComodidade(nomeEvento, nomeEvento, preco, Categoria.CUSTO_FIXO);
            }
            else if (variavel.isSelected()) {
                controlador.adicionarComodidade(nomeEvento, nomeEvento, preco, Categoria.CUSTO_VARIAVEL);
            }
            
        }
    }//GEN-LAST:event_adiconarComodidadeActionPerformed

    private void exibirNotificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirNotificacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exibirNotificacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEvento;
    private javax.swing.JButton adiconarComodidade;
    private javax.swing.JButton alterarDadosEvento;
    private javax.swing.JButton buscarEvento;
    private javax.swing.JButton cancelarEvento;
    private javax.swing.JButton criarOrganizador;
    private javax.swing.JButton exibirEvento;
    private javax.swing.JButton exibirNotificacoes;
    private javax.swing.JButton exibirRelatorioEventos;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    // End of variables declaration//GEN-END:variables
}
