package Interface;

import Controle.Controlador;
import Modelo.CategoriaCusto;
import Modelo.Localizacao;
import Modelo.Status;
import Modelo.TipoItem;
import java.awt.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;

/**
 *
 * @author Sayu
 */
public class Menu extends javax.swing.JFrame {

    private Controlador controlador;

    public Menu() {
        controlador = new Controlador(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        exibirRelatorioEventos = new javax.swing.JButton();
        buscarEvento = new javax.swing.JButton();
        removerFuncionario = new javax.swing.JButton();
        removerItemBuffet = new javax.swing.JButton();
        removerDespesaAdicional = new javax.swing.JButton();
        registrarEvento = new javax.swing.JButton();
        registrarDespesaAdicional = new javax.swing.JButton();
        cancelarEvento = new javax.swing.JButton();
        alterarStatus = new javax.swing.JButton();
        alterarDespesasAdicionais = new javax.swing.JButton();
        inserirItemBuffet = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));

        exibirRelatorioEventos.setBackground(new java.awt.Color(255, 204, 204));
        exibirRelatorioEventos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exibirRelatorioEventos.setForeground(new java.awt.Color(204, 0, 51));
        exibirRelatorioEventos.setText("Exibir Relatório dos Eventos");
        exibirRelatorioEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirRelatorioEventosActionPerformed(evt);
            }
        });

        buscarEvento.setBackground(new java.awt.Color(255, 204, 204));
        buscarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buscarEvento.setForeground(new java.awt.Color(204, 0, 51));
        buscarEvento.setText("Buscar Evento");
        buscarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEventoActionPerformed(evt);
            }
        });

        removerFuncionario.setBackground(new java.awt.Color(255, 204, 204));
        removerFuncionario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removerFuncionario.setForeground(new java.awt.Color(204, 0, 51));
        removerFuncionario.setText("Remover Funcionário");
        removerFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerFuncionarioActionPerformed(evt);
            }
        });

        removerItemBuffet.setBackground(new java.awt.Color(255, 204, 204));
        removerItemBuffet.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removerItemBuffet.setForeground(new java.awt.Color(204, 0, 51));
        removerItemBuffet.setText("Remover Item Buffet");
        removerItemBuffet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemBuffetActionPerformed(evt);
            }
        });

        removerDespesaAdicional.setBackground(new java.awt.Color(255, 204, 204));
        removerDespesaAdicional.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removerDespesaAdicional.setForeground(new java.awt.Color(204, 0, 51));
        removerDespesaAdicional.setText("Remover Despesa Adicional");
        removerDespesaAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerDespesaAdicionalActionPerformed(evt);
            }
        });

        registrarEvento.setBackground(new java.awt.Color(255, 204, 204));
        registrarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        registrarEvento.setForeground(new java.awt.Color(204, 0, 51));
        registrarEvento.setText("Registrar Evento");
        registrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEventoActionPerformed(evt);
            }
        });

        registrarDespesaAdicional.setBackground(new java.awt.Color(255, 204, 204));
        registrarDespesaAdicional.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        registrarDespesaAdicional.setForeground(new java.awt.Color(204, 0, 51));
        registrarDespesaAdicional.setText("Inserir Despesa Adicional");
        registrarDespesaAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarDespesaAdicionalActionPerformed(evt);
            }
        });

        cancelarEvento.setBackground(new java.awt.Color(255, 204, 204));
        cancelarEvento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cancelarEvento.setForeground(new java.awt.Color(204, 0, 51));
        cancelarEvento.setText("Cancelar Evento");
        cancelarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEventoActionPerformed(evt);
            }
        });

        alterarStatus.setBackground(new java.awt.Color(255, 204, 204));
        alterarStatus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        alterarStatus.setForeground(new java.awt.Color(204, 0, 51));
        alterarStatus.setText("Alterar Status Evento");
        alterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarStatusActionPerformed(evt);
            }
        });

        alterarDespesasAdicionais.setBackground(new java.awt.Color(255, 204, 204));
        alterarDespesasAdicionais.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        alterarDespesasAdicionais.setForeground(new java.awt.Color(204, 0, 51));
        alterarDespesasAdicionais.setText("Alterar Despesas Adicionais");
        alterarDespesasAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDespesasAdicionaisActionPerformed(evt);
            }
        });

        inserirItemBuffet.setBackground(new java.awt.Color(255, 204, 204));
        inserirItemBuffet.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        inserirItemBuffet.setForeground(new java.awt.Color(204, 0, 51));
        inserirItemBuffet.setText("Inserir Item Buffet");
        inserirItemBuffet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirItemBuffetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inserirItemBuffet)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alterarDespesasAdicionais)
                            .addComponent(removerItemBuffet)
                            .addComponent(exibirRelatorioEventos)
                            .addComponent(registrarEvento)
                            .addComponent(removerDespesaAdicional)
                            .addComponent(removerFuncionario)
                            .addComponent(alterarStatus)
                            .addComponent(registrarDespesaAdicional)
                            .addComponent(buscarEvento)
                            .addComponent(cancelarEvento))
                        .addGap(196, 515, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerDespesaAdicional)
                .addGap(18, 18, 18)
                .addComponent(removerItemBuffet)
                .addGap(18, 18, 18)
                .addComponent(removerFuncionario)
                .addGap(18, 18, 18)
                .addComponent(exibirRelatorioEventos)
                .addGap(18, 18, 18)
                .addComponent(registrarDespesaAdicional)
                .addGap(18, 18, 18)
                .addComponent(cancelarEvento)
                .addGap(18, 18, 18)
                .addComponent(buscarEvento)
                .addGap(18, 18, 18)
                .addComponent(alterarStatus)
                .addGap(18, 18, 18)
                .addComponent(alterarDespesasAdicionais)
                .addGap(18, 18, 18)
                .addComponent(inserirItemBuffet)
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void exibirMensagemDeConfirmacao()
    {
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Operação concluída"));

        JOptionPane.showMessageDialog(null, "Operação concluída", "Aviso", 1);
    }
    
    public void exibirMensagemDeErro()
    {
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Erro detectado"));

        JOptionPane.showMessageDialog(null, "Erro detectado", "Aviso", 0);
    }
    
    private void exibirRelatorioEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirRelatorioEventosActionPerformed
        // TODO add your handling code here:
        String texto = controlador.exibirelatorioEventos();
        JTextArea evento = new JTextArea(texto, 20, 50);
        evento.setLineWrap(true);
        evento.setWrapStyleWord(true);
        evento.setEditable(false);

        JScrollPane scroll = new JScrollPane(evento);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        JFrame frame = new JFrame("Exibição de Texto Grande");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(scroll);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_exibirRelatorioEventosActionPerformed

    private void buscarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEventoActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(nomeField);
        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
                frame, panel,
                "Buscar Evento",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = nomeField.getText();
            String texto = controlador.exibirEvento(nomeEvento);
            
            JOptionPane.showMessageDialog(null, texto);
        }
    }//GEN-LAST:event_buscarEventoActionPerformed

    private void removerFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerFuncionarioActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Funcionario:"));
        panel.add(nomeField);
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Funcionario",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeFuncionario = nomeField.getText();
            String nomeEvento = eventoField.getText();
            controlador.removerFuncionario(nomeEvento, nomeFuncionario);
        }
    }//GEN-LAST:event_removerFuncionarioActionPerformed

    private void removerItemBuffetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemBuffetActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Item do buffet:"));
        panel.add(nomeField);
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Item do buffet",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeItemBuffet = nomeField.getText();
            String nomeEvento = eventoField.getText();
            controlador.removerItemBuffet(nomeEvento, nomeItemBuffet);
        }
    }//GEN-LAST:event_removerItemBuffetActionPerformed

    private void removerDespesaAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerDespesaAdicionalActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome da Despesa adicional:"));
        panel.add(nomeField);
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Despesa Adicional",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeDespesaAdicional = nomeField.getText();
            String nomeEvento = eventoField.getText();
            controlador.removerDespesaAdicional(nomeEvento, nomeDespesaAdicional);
        }
    }//GEN-LAST:event_removerDespesaAdicionalActionPerformed

    private void registrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEventoActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField descricaoField = new JTextField(15);
        JTextField quantidadeField = new JTextField(5);
        JTextField localField = new JTextField(10);
        JTextField longitudeField = new JTextField(10);
        JTextField latitudeField = new JTextField(10);
        JTextField aluguelDiarioField = new JTextField(10);
        JTextField inicioField = new JTextField(15);
        JTextField fimField = new JTextField(15);

        // Criando painel para organizar os inputs
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Descrição:"));
        panel.add(descricaoField);
        panel.add(new JLabel("Quantidade:"));
        panel.add(quantidadeField);
        panel.add(new JLabel("Nome do local:"));
        panel.add(localField);
        panel.add(new JLabel("Longitude:"));
        panel.add(longitudeField);
        panel.add(new JLabel("Latitude:"));
        panel.add(latitudeField);
        panel.add(new JLabel("Aluguel Diario:"));
        panel.add(aluguelDiarioField);
        panel.add(new JLabel("Data inicio (exmplo:2025-11-03 10:30:00):"));
        panel.add(inicioField);
        panel.add(new JLabel("Data fim (exmplo:2025-11-03 10:30:00):"));
        panel.add(fimField);
        
        Component frame = null;
        
        // Exibindo o JOptionPane
        int result = JOptionPane.showConfirmDialog(
                frame, panel,
                "Preencha as informações",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        // Pegando os valores se o usuário clicar em OK
        if (result == JOptionPane.OK_OPTION) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            LocalDateTime dataHoraInicio = LocalDateTime.parse(inicioField.getText(), formatter);
            LocalDateTime dataHoraFim = LocalDateTime.parse(fimField.getText(), formatter);
            controlador.validarInputsDeRegistroDoEvento(nomeField.getText(), descricaoField.getText(), Integer.parseInt(quantidadeField.getText()), dataHoraInicio, dataHoraFim);
        }
    }//GEN-LAST:event_registrarEventoActionPerformed

    private void registrarDespesaAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarDespesaAdicionalActionPerformed
        // TODO add your handling code here:
        JTextField eventoField = new JTextField(15);
        JTextField nomeField = new JTextField(15);
        JTextField catField = new JTextField(15);
        JTextField descricaoField = new JTextField(15);
        JTextField custoPorPessoaField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);
        panel.add(new JLabel("Nome da Despesa adicional:"));
        panel.add(nomeField);
        panel.add(new JLabel("Categoria CUSTO_FIXO ou CUSTO_VARIAVEL:"));
        panel.add(catField);
        panel.add(new JLabel("Descrição:"));
        panel.add(descricaoField);
        panel.add(new JLabel("Custo por pessoa:"));
        panel.add(custoPorPessoaField);
        
        

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Preencha as informações",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            String nomeDespesa = nomeField.getText();
            String descricao = descricaoField.getText();
            
            if(catField.getText().equals("CUSTO_FIXO"))
            {
                controlador.validarInputsDeRegistroDeDespesaAdicional(nomeEvento, nomeDespesa, CategoriaCusto.CUSTO_FIXO, descricao, Double.parseDouble(custoPorPessoaField.getText()));
            }
            else if(catField.getText().equals("CUSTO_VARIAVEL"))
            {
                controlador.validarInputsDeRegistroDeDespesaAdicional(nomeEvento, nomeDespesa, CategoriaCusto.CUSTO_VARIAVEL, descricao, Double.parseDouble(custoPorPessoaField.getText()));
            }
        }
    }//GEN-LAST:event_registrarDespesaAdicionalActionPerformed

    private void cancelarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEventoActionPerformed
        // TODO add your handling code here:
        JTextField eventoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);
        
        Component frame = null;
        
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Preencha as informações",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            controlador.cancelarEvento(nomeEvento);
        }
    }//GEN-LAST:event_cancelarEventoActionPerformed

    private void alterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarStatusActionPerformed
        // TODO add your handling code here:
        JTextField eventoField = new JTextField(15);
        JTextField statusField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);
        panel.add(new JLabel("Novo status AGENDAMENTO, EM_ANDAMENTO, ENCERRADO:"));
        panel.add(statusField);
        
        Component frame = null;
        
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Preencha as informações",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            if(statusField.getText().equals("AGENDAMENTO"))
            {
                controlador.alterarStatus(nomeEvento, Status.AGENDAMENTO);
            }
            else if(statusField.getText().equals("EM_ANDAMENTO"))
            {
                controlador.alterarStatus(nomeEvento, Status.EM_ANDAMENTO);
            }
            else if(statusField.getText().equals("ENCERRADO"))
            {
                controlador.alterarStatus(nomeEvento, Status.ENCERRADO);
            }
        }
        
    }//GEN-LAST:event_alterarStatusActionPerformed

    private void alterarDespesasAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDespesasAdicionaisActionPerformed
        // TODO add your handling code here:
        JTextField eventoField = new JTextField(15);
        JTextField nomeField = new JTextField(15);
        JTextField novonomeField = new JTextField(15);
        JTextField novacatField = new JTextField(15);
        JTextField novadescricaoField = new JTextField(15);
        JTextField novocustoPorPessoaField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);
        panel.add(new JLabel("Nome da Despesa adicional:"));
        panel.add(nomeField);
        panel.add(new JLabel("Novo Nome da Despesa adicional:"));
        panel.add(novonomeField);
        panel.add(new JLabel("Nova Categoria CUSTO_FIXO ou CUSTO_VARIAVEL:"));
        panel.add(novacatField);
        panel.add(new JLabel("Nova Descrição:"));
        panel.add(novadescricaoField);
        panel.add(new JLabel("Novo Custo por pessoa:"));
        panel.add(novocustoPorPessoaField);
        
        

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Preencha as informações",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            String nomeDespesa = nomeField.getText();
            String descricao = novadescricaoField.getText();
            
            if(novacatField.getText().equals("CUSTO_FIXO"))
            {
                controlador.validarInputsDeAlteracaoDeDespesaAdicional(nomeEvento, nomeDespesa, novonomeField.getText(), CategoriaCusto.CUSTO_FIXO, descricao, Double.parseDouble(novocustoPorPessoaField.getText()));
            }
            else if(novacatField.getText().equals("CUSTO_VARIAVEL"))
            {
                controlador.validarInputsDeAlteracaoDeDespesaAdicional(nomeEvento, nomeDespesa, novonomeField.getText(), CategoriaCusto.CUSTO_VARIAVEL, descricao, Double.parseDouble(novocustoPorPessoaField.getText()));
            }
        }
    }//GEN-LAST:event_alterarDespesasAdicionaisActionPerformed

    private void inserirItemBuffetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirItemBuffetActionPerformed
        // TODO add your handling code here:
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        JTextField tipoField = new JTextField(15);
        JTextField custoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Item do buffet:"));
        panel.add(nomeField);
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);
        panel.add(new JLabel("Tipo BEBIDA ou COMIDA:"));
        panel.add(tipoField);
        panel.add(new JLabel("Custo:"));
        panel.add(custoField);
        
        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Item do buffet",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeItemBuffet = nomeField.getText();
            String nomeEvento = eventoField.getText();
            if(tipoField.getText().equals("BEBIDA"))
            {
                controlador.validarInputsDeRegistroDeItemDoBuffet(nomeEvento, nomeItemBuffet, TipoItem.BEBIDA, Double.parseDouble(custoField.getText()));
            }
            else if(tipoField.getText().equals("COMIDA"))
            {
                controlador.validarInputsDeRegistroDeItemDoBuffet(nomeEvento, nomeItemBuffet, TipoItem.COMIDA, Double.parseDouble(custoField.getText()));
            }
            
        }
    }//GEN-LAST:event_inserirItemBuffetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarDespesasAdicionais;
    private javax.swing.JButton alterarStatus;
    private javax.swing.JButton buscarEvento;
    private javax.swing.JButton cancelarEvento;
    private javax.swing.JButton exibirRelatorioEventos;
    private javax.swing.JButton inserirItemBuffet;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JButton registrarDespesaAdicional;
    private javax.swing.JButton registrarEvento;
    private javax.swing.JButton removerDespesaAdicional;
    private javax.swing.JButton removerFuncionario;
    private javax.swing.JButton removerItemBuffet;
    // End of variables declaration//GEN-END:variables
}
